// swift-tools-version: 5.9
// Citadel for macOS (and later iOS): a SwiftUI host over the Rust core.
//
// Build the core first (`cargo build -p citadel-ffi` from the repo root; add
// `--release` and point CITADEL_RUST_TARGET_DIR/profile accordingly), then
// `swift build` / `swift run CitadelApp` here. The generated binding under
// Sources/Citadel and the C header under Sources/CitadelFFI/include are
// regenerated by `scripts/generate-bindings.sh`.
import PackageDescription
import Foundation

let rustTargetDir = ProcessInfo.processInfo.environment["CITADEL_RUST_TARGET_DIR"] ?? "../../target"
let rustProfile = ProcessInfo.processInfo.environment["CITADEL_RUST_PROFILE"] ?? "debug"
let rustLibDir = "\(rustTargetDir)/\(rustProfile)"

let package = Package(
    name: "Citadel",
    platforms: [.macOS(.v14)],
    products: [
        .executable(name: "CitadelApp", targets: ["CitadelApp"]),
        .library(name: "Citadel", targets: ["Citadel"]),
    ],
    targets: [
        // The C ABI of libcitadel_ffi (UniFFI-generated header + modulemap).
        .target(
            name: "CitadelFFI",
            path: "Sources/CitadelFFI",
            publicHeadersPath: "include"
        ),
        // The generated Swift binding, linked against the Rust staticlib.
        .target(
            name: "Citadel",
            dependencies: ["CitadelFFI"],
            path: "Sources/Citadel",
            linkerSettings: [
                .unsafeFlags(["-L", rustLibDir]),
                .linkedLibrary("citadel_ffi"),
                .linkedFramework("Security"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("SystemConfiguration"),
            ]
        ),
        .executableTarget(
            name: "CitadelApp",
            dependencies: ["Citadel"],
            path: "Sources/CitadelApp"
        ),
    ]
)
