// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(citadel_ffiFFI)
import citadel_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_citadel_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_citadel_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCitadelFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * One profile. Hold one per signed-in account.
 */
public protocol ClientProtocol: AnyObject, Sendable {
    
    func conversations() throws  -> [Conversation]
    
    /**
     * Open a DM with KT-verified peers (handles). Returns the group id.
     */
    func createDm(handles: [String], title: String?) throws  -> String
    
    func login() throws  -> Profile
    
    /**
     * KT-verify a peer by handle.
     */
    func lookup(handle: String) throws  -> Peer
    
    func messages(groupId: String) throws  -> [Message]
    
    func profile() throws  -> Profile?
    
    func register(handle: String) throws  -> Profile
    
    func send(groupId: String, text: String) throws 
    
    /**
     * Hold the gateway open in the background (reconnecting) and forward
     * every event to `listener`. Requires a login. Idempotent.
     */
    func startGateway(listener: EventListener) 
    
    func stopGateway() 
    
    func sync() throws 
    
}
/**
 * One profile. Hold one per signed-in account.
 */
open class Client: ClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_citadel_ffi_fn_clone_client(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_citadel_ffi_fn_free_client(handle, $0) }
    }

    
    /**
     * Open (or create) the profile at `profile_root`. `credential_service`
     * names the OS credential-store entries (use one per profile);
     * `auth_url`/`delivery_url` are the service bases; `kt_anchor_hex` is
     * the log's Ed25519 public key (64 hex chars) — a shipped host embeds it.
     */
public static func `open`(profileRoot: String, credentialService: String, authUrl: String, deliveryUrl: String, ktAnchorHex: String)throws  -> Client  {
    return try  FfiConverterTypeClient_lift(try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_constructor_client_open(
        FfiConverterString.lower(profileRoot),
        FfiConverterString.lower(credentialService),
        FfiConverterString.lower(authUrl),
        FfiConverterString.lower(deliveryUrl),
        FfiConverterString.lower(ktAnchorHex),uniffiCallStatus
    )
})
}
    
    /**
     * The dev stack's log anchor, derived from the public dev seed. Never
     * use in a shipped host.
     */
public static func openDev(profileRoot: String, credentialService: String)throws  -> Client  {
    return try  FfiConverterTypeClient_lift(try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_constructor_client_open_dev(
        FfiConverterString.lower(profileRoot),
        FfiConverterString.lower(credentialService),uniffiCallStatus
    )
})
}
    

    
open func conversations()throws  -> [Conversation]  {
    return try  FfiConverterSequenceTypeConversation.lift(try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_conversations(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Open a DM with KT-verified peers (handles). Returns the group id.
     */
open func createDm(handles: [String], title: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_create_dm(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(handles),
        FfiConverterOptionString.lower(title),uniffiCallStatus
    )
})
}
    
open func login()throws  -> Profile  {
    return try  FfiConverterTypeProfile_lift(try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_login(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * KT-verify a peer by handle.
     */
open func lookup(handle: String)throws  -> Peer  {
    return try  FfiConverterTypePeer_lift(try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_lookup(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(handle),uniffiCallStatus
    )
})
}
    
open func messages(groupId: String)throws  -> [Message]  {
    return try  FfiConverterSequenceTypeMessage.lift(try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_messages(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(groupId),uniffiCallStatus
    )
})
}
    
open func profile()throws  -> Profile?  {
    return try  FfiConverterOptionTypeProfile.lift(try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_profile(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func register(handle: String)throws  -> Profile  {
    return try  FfiConverterTypeProfile_lift(try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_register(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(handle),uniffiCallStatus
    )
})
}
    
open func send(groupId: String, text: String)throws   {try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_send(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(groupId),
        FfiConverterString.lower(text),uniffiCallStatus
    )
}
}
    
    /**
     * Hold the gateway open in the background (reconnecting) and forward
     * every event to `listener`. Requires a login. Idempotent.
     */
open func startGateway(listener: EventListener)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_start_gateway(
            self.uniffiCloneHandle(),
        FfiConverterCallbackInterfaceEventListener_lower(listener),uniffiCallStatus
    )
}
}
    
open func stopGateway()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_stop_gateway(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
open func sync()throws   {try rustCallWithError(FfiConverterTypeCitadelError_lift) {
        uniffiCallStatus in
    uniffi_citadel_ffi_fn_method_client_sync(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Client

    public static func lift(_ handle: UInt64) throws -> Client {
        return Client(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Client) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Client {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Client, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClient_lift(_ handle: UInt64) throws -> Client {
    return try FfiConverterTypeClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClient_lower(_ value: Client) -> UInt64 {
    return FfiConverterTypeClient.lower(value)
}




public struct Conversation: Equatable, Hashable {
    public var groupId: String
    public var title: String?
    public var epoch: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(groupId: String, title: String?, epoch: UInt64) {
        self.groupId = groupId
        self.title = title
        self.epoch = epoch
    }

    

    
}

#if compiler(>=6)
extension Conversation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConversation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Conversation {
        return
            try Conversation(
                groupId: FfiConverterString.read(from: &buf), 
                title: FfiConverterOptionString.read(from: &buf), 
                epoch: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Conversation, into buf: inout [UInt8]) {
        FfiConverterString.write(value.groupId, into: &buf)
        FfiConverterOptionString.write(value.title, into: &buf)
        FfiConverterUInt64.write(value.epoch, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversation_lift(_ buf: RustBuffer) throws -> Conversation {
    return try FfiConverterTypeConversation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversation_lower(_ value: Conversation) -> RustBuffer {
    return FfiConverterTypeConversation.lower(value)
}


public struct Message: Equatable, Hashable {
    public var id: Int64
    public var groupId: String
    public var outgoing: Bool
    public var epoch: UInt64
    public var text: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, groupId: String, outgoing: Bool, epoch: UInt64, text: String) {
        self.id = id
        self.groupId = groupId
        self.outgoing = outgoing
        self.epoch = epoch
        self.text = text
    }

    

    
}

#if compiler(>=6)
extension Message: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Message {
        return
            try Message(
                id: FfiConverterInt64.read(from: &buf), 
                groupId: FfiConverterString.read(from: &buf), 
                outgoing: FfiConverterBool.read(from: &buf), 
                epoch: FfiConverterUInt64.read(from: &buf), 
                text: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Message, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.groupId, into: &buf)
        FfiConverterBool.write(value.outgoing, into: &buf)
        FfiConverterUInt64.write(value.epoch, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lift(_ buf: RustBuffer) throws -> Message {
    return try FfiConverterTypeMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lower(_ value: Message) -> RustBuffer {
    return FfiConverterTypeMessage.lower(value)
}


public struct Peer: Equatable, Hashable {
    public var accountId: String
    public var handle: String
    public var identityPubkeyHex: String
    public var ktLeafIndex: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(accountId: String, handle: String, identityPubkeyHex: String, ktLeafIndex: UInt64) {
        self.accountId = accountId
        self.handle = handle
        self.identityPubkeyHex = identityPubkeyHex
        self.ktLeafIndex = ktLeafIndex
    }

    

    
}

#if compiler(>=6)
extension Peer: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePeer: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Peer {
        return
            try Peer(
                accountId: FfiConverterString.read(from: &buf), 
                handle: FfiConverterString.read(from: &buf), 
                identityPubkeyHex: FfiConverterString.read(from: &buf), 
                ktLeafIndex: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Peer, into buf: inout [UInt8]) {
        FfiConverterString.write(value.accountId, into: &buf)
        FfiConverterString.write(value.handle, into: &buf)
        FfiConverterString.write(value.identityPubkeyHex, into: &buf)
        FfiConverterUInt64.write(value.ktLeafIndex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePeer_lift(_ buf: RustBuffer) throws -> Peer {
    return try FfiConverterTypePeer.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePeer_lower(_ value: Peer) -> RustBuffer {
    return FfiConverterTypePeer.lower(value)
}


public struct Profile: Equatable, Hashable {
    public var accountId: String
    public var deviceId: String
    public var handle: String
    public var identityPubkeyHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(accountId: String, deviceId: String, handle: String, identityPubkeyHex: String) {
        self.accountId = accountId
        self.deviceId = deviceId
        self.handle = handle
        self.identityPubkeyHex = identityPubkeyHex
    }

    

    
}

#if compiler(>=6)
extension Profile: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProfile: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Profile {
        return
            try Profile(
                accountId: FfiConverterString.read(from: &buf), 
                deviceId: FfiConverterString.read(from: &buf), 
                handle: FfiConverterString.read(from: &buf), 
                identityPubkeyHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Profile, into buf: inout [UInt8]) {
        FfiConverterString.write(value.accountId, into: &buf)
        FfiConverterString.write(value.deviceId, into: &buf)
        FfiConverterString.write(value.handle, into: &buf)
        FfiConverterString.write(value.identityPubkeyHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProfile_lift(_ buf: RustBuffer) throws -> Profile {
    return try FfiConverterTypeProfile.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProfile_lower(_ value: Profile) -> RustBuffer {
    return FfiConverterTypeProfile.lower(value)
}


public 
enum CitadelError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Failed(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CitadelError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCitadelError: FfiConverterRustBuffer {
    typealias SwiftType = CitadelError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CitadelError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Failed(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CitadelError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Failed(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCitadelError_lift(_ buf: RustBuffer) throws -> CitadelError {
    return try FfiConverterTypeCitadelError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCitadelError_lower(_ value: CitadelError) -> RustBuffer {
    return FfiConverterTypeCitadelError.lower(value)
}



public enum Event: Equatable, Hashable {
    
    case registered(profile: Profile
    )
    case loggedIn
    case conversationCreated(groupId: String
    )
    case conversationJoined(groupId: String
    )
    case messageSent(groupId: String
    )
    case messageReceived(groupId: String, epoch: UInt64, text: String
    )
    case epochAdvanced(groupId: String, epoch: UInt64
    )
    case gatewayConnected
    case gatewayDisconnected
    case warning(text: String
    )





}

#if compiler(>=6)
extension Event: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEvent: FfiConverterRustBuffer {
    typealias SwiftType = Event

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Event {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .registered(profile: try FfiConverterTypeProfile.read(from: &buf)
        )
        
        case 2: return .loggedIn
        
        case 3: return .conversationCreated(groupId: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .conversationJoined(groupId: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .messageSent(groupId: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .messageReceived(groupId: try FfiConverterString.read(from: &buf), epoch: try FfiConverterUInt64.read(from: &buf), text: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .epochAdvanced(groupId: try FfiConverterString.read(from: &buf), epoch: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 8: return .gatewayConnected
        
        case 9: return .gatewayDisconnected
        
        case 10: return .warning(text: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Event, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .registered(profile):
            writeInt(&buf, Int32(1))
            FfiConverterTypeProfile.write(profile, into: &buf)
            
        
        case .loggedIn:
            writeInt(&buf, Int32(2))
        
        
        case let .conversationCreated(groupId):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(groupId, into: &buf)
            
        
        case let .conversationJoined(groupId):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(groupId, into: &buf)
            
        
        case let .messageSent(groupId):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(groupId, into: &buf)
            
        
        case let .messageReceived(groupId,epoch,text):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(groupId, into: &buf)
            FfiConverterUInt64.write(epoch, into: &buf)
            FfiConverterString.write(text, into: &buf)
            
        
        case let .epochAdvanced(groupId,epoch):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(groupId, into: &buf)
            FfiConverterUInt64.write(epoch, into: &buf)
            
        
        case .gatewayConnected:
            writeInt(&buf, Int32(8))
        
        
        case .gatewayDisconnected:
            writeInt(&buf, Int32(9))
        
        
        case let .warning(text):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(text, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEvent_lift(_ buf: RustBuffer) throws -> Event {
    return try FfiConverterTypeEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEvent_lower(_ value: Event) -> RustBuffer {
    return FfiConverterTypeEvent.lower(value)
}





/**
 * Implemented by the host. Called from a background thread.
 */
public protocol EventListener: AnyObject, Sendable {
    
    func onEvent(event: Event) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEventListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceEventListener = UniffiVTableCallbackInterfaceEventListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceEventListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface EventListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceEventListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface EventListener: handle missing in uniffiClone")
            }
        },
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeEvent_lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceEventListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceEventListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitEventListener() {
    uniffi_citadel_ffi_fn_init_callback_vtable_eventlistener(UniffiCallbackInterfaceEventListener.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceEventListener {
    fileprivate static let handleMap = UniffiHandleMap<EventListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceEventListener : FfiConverter {
    typealias SwiftType = EventListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEventListener_lift(_ handle: UInt64) throws -> EventListener {
    return try FfiConverterCallbackInterfaceEventListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEventListener_lower(_ v: EventListener) -> UInt64 {
    return FfiConverterCallbackInterfaceEventListener.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeProfile: FfiConverterRustBuffer {
    typealias SwiftType = Profile?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeProfile.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeProfile.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeConversation: FfiConverterRustBuffer {
    typealias SwiftType = [Conversation]

    public static func write(_ value: [Conversation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeConversation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Conversation] {
        let len: Int32 = try readInt(&buf)
        var seq = [Conversation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeConversation.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMessage: FfiConverterRustBuffer {
    typealias SwiftType = [Message]

    public static func write(_ value: [Message], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Message] {
        let len: Int32 = try readInt(&buf)
        var seq = [Message]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMessage.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_citadel_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_conversations() != 10301) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_create_dm() != 49509) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_login() != 61970) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_lookup() != 56108) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_messages() != 26987) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_profile() != 50739) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_register() != 26106) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_send() != 18425) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_start_gateway() != 13749) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_stop_gateway() != 26096) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_client_sync() != 54450) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_constructor_client_open() != 32264) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_constructor_client_open_dev() != 12274) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_citadel_ffi_checksum_method_eventlistener_on_event() != 62765) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitEventListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCitadelFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all