// Command merkle-go emits the RFC 6962 cross-check fixture corpus for
// crates/kt-log. Run from this directory:
//
//	go run . > ../../../kt-log/tests/fixtures/merkle_rfc6962.json
//
// The output is deterministic: same corpora in, byte-identical JSON out, so a
// regenerate-and-diff CI step (owned by K3) can detect any drift between the
// oracle and the committed fixtures.
package main

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
)

// fixtureFile is the top-level committed artifact.
type fixtureFile struct {
	Generator string   `json:"generator"`
	Spec      string   `json:"spec"`
	Hash      string   `json:"hash"`
	Note      string   `json:"note"`
	Corpora   []corpus `json:"corpora"`
}

type corpus struct {
	Name        string            `json:"name"`
	Note        string            `json:"note"`
	Leaves      []string          `json:"leaves"` // hex of each raw leaf entry
	Roots       []rootCase        `json:"roots"`  // one per tree_size 0..=N
	Inclusion   []inclusionCase   `json:"inclusion"`
	Consistency []consistencyCase `json:"consistency"`
}

type rootCase struct {
	TreeSize int    `json:"tree_size"`
	Root     string `json:"root"`
}

type inclusionCase struct {
	TreeSize  int      `json:"tree_size"`
	LeafIndex int      `json:"leaf_index"`
	Path      []string `json:"path"`
}

type consistencyCase struct {
	First  int      `json:"first"`
	Second int      `json:"second"`
	Path   []string `json:"path"`
}

func hexOf(b []byte) string { return hex.EncodeToString(b) }

func pathHex(hs [][]byte) []string {
	out := make([]string, 0, len(hs))
	for _, h := range hs {
		out = append(out, hexOf(h))
	}
	return out
}

// buildCorpus derives every root, inclusion path, and consistency path the
// fixture exercises, exhaustively over all valid sizes/indices/pairs.
func buildCorpus(name, note string, entries [][]byte) corpus {
	n := len(entries)
	c := corpus{Name: name, Note: note}

	c.Leaves = make([]string, n)
	for i, e := range entries {
		c.Leaves[i] = hexOf(e)
	}

	// Roots for every tree size, including the empty tree (size 0).
	for size := 0; size <= n; size++ {
		c.Roots = append(c.Roots, rootCase{
			TreeSize: size,
			Root:     hexOf(merkleTreeHash(entries[:size])),
		})
	}

	// Inclusion proof for every (tree_size, leaf_index) with the leaf present.
	for size := 1; size <= n; size++ {
		for idx := 0; idx < size; idx++ {
			c.Inclusion = append(c.Inclusion, inclusionCase{
				TreeSize:  size,
				LeafIndex: idx,
				Path:      pathHex(auditPath(idx, entries[:size])),
			})
		}
	}

	// Consistency proof for every (first, second) with 0 < first <= second.
	for second := 1; second <= n; second++ {
		for first := 1; first <= second; first++ {
			c.Consistency = append(c.Consistency, consistencyCase{
				First:  first,
				Second: second,
				Path:   pathHex(consistencyProof(first, entries[:second])),
			})
		}
	}
	return c
}

// ctReferenceLeaves are the Certificate Transparency reference test entries
// (RFC 6962 test vectors). Their roots are externally published, so this
// corpus also anchors the oracle itself to known-good values — the fixtures
// are not merely self-consistent, they reproduce the canonical CT roots.
func ctReferenceLeaves() [][]byte {
	return [][]byte{
		{},
		{0x00},
		{0x10},
		{0x20, 0x21},
		{0x30, 0x31},
		{0x40, 0x41, 0x42, 0x43},
		{0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57},
		{0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f},
	}
}

// extendedLeaves is a distinct 16-entry corpus that stresses non-power-of-two
// split points and long audit/consistency paths beyond the 8-leaf CT set.
// Entries are deterministic and varied in length (including one empty entry)
// so the cross-check covers leaf-length handling, not just fixed 32-byte data.
func extendedLeaves() [][]byte {
	entries := make([][]byte, 16)
	for i := 0; i < 16; i++ {
		// A varied-length payload seeded by the index; index 0 stays empty to
		// exercise the empty-entry leaf hash alongside non-empty siblings.
		e := make([]byte, i) // lengths 0..15
		for j := range e {
			e[j] = byte((i*31 + j*7) & 0xff)
		}
		entries[i] = e
	}
	return entries
}

func main() {
	f := fixtureFile{
		Generator: "citadel test-harness/oracles/merkle-go (independent Go RFC 6962 oracle)",
		Spec:      "RFC 6962 §2.1 (MTH, PATH, SUBPROOF); verified by RFC 9162 §2.1.3/§2.1.4",
		Hash:      "SHA-256",
		Note: "Test-time cross-check fixtures for crates/kt-log. Generated by an " +
			"independent implementation; do not hand-edit — regenerate with `go run .`.",
		Corpora: []corpus{
			buildCorpus("ct-reference",
				"Certificate Transparency reference entries; roots match published CT vectors.",
				ctReferenceLeaves()),
			buildCorpus("extended-16",
				"16 deterministic varied-length entries stressing non-power-of-two trees.",
				extendedLeaves()),
		},
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(&f); err != nil {
		fmt.Fprintln(os.Stderr, "encode:", err)
		os.Exit(1)
	}
}
